### PR TITLE
transcoder: Fix flacenc "insane" level encoding

### LINKED ISSUE #6876: Cant rip as flac best quality
Please provide information about your system and the version of Clementine used.

- Operating System: Linux Mint 20.1
- Clementine version:  1.4.0rc1-398-g0393d865c

### Expected behaviour / actual behaviour
To be able to rip FLACS
### Steps to reproduce the problem (only for bugs)
Rip cd choose flac
in options move quality up to best 
flacs will rip as 0 byte files. 
I am unsure if flacs work in other qualities

### PR DESCRIPTION
**Pull request by jbroadus**
The gstreamer flacenc element defines a set of quality levels that is different
from the standard flac library. Its highest level, labeled "insane", uses
settings that are outside of the streamable subset. Set the streamable-subset
property to false for this level.

Reference: https://xiph.org/flac/format.html#subset

Fixes #6876

### CODE REVIEW

File: src/transcoder/transcoderoptionsflac.cpp [hunk 1]
```diff
@@ -37,9 +39,30 @@ void TranscoderOptionsFlac::Load() {
   ui_->quality->setValue(s.value("quality", 5).toInt());
 }
 
+void TranscoderOptionsFlac::ValueChanged(int value) {
+  if (!IsInStreamingSubset(value)) {
+    ui_->info->setStyleSheet("QLabel { color : red }");
+    ui_->info->setText(
+        tr("Warning: This compression level is outside of the streamable "
```
Comment (hatstand) [inline src/transcoder/transcoderoptionsflac.cpp:46]: You might want to expand on what the practical implications of that are.

File: src/transcoder/transcoderoptionsflac.cpp [hunk 2]
```diff
@@ -37,9 +39,30 @@ void TranscoderOptionsFlac::Load() {
   ui_->quality->setValue(s.value("quality", 5).toInt());
 }
 
+void TranscoderOptionsFlac::ValueChanged(int value) {
+  if (!IsInStreamingSubset(value)) {
+    ui_->info->setStyleSheet("QLabel { color : red }");
```
Comment (hatstand) [inline src/transcoder/transcoderoptionsflac.cpp:44]: I think you need to unset this in the `else` block.

File: src/transcoder/transcoderoptionsflac.cpp [hunk 3]
```diff
@@ -37,9 +39,30 @@ void TranscoderOptionsFlac::Load() {
...
+
 void TranscoderOptionsFlac::Save() {
   QSettings s;
   s.beginGroup(kSettingsGroup + settings_postfix_);
 
-  s.setValue("quality", ui_->quality->value());
+  int quality = ui_->quality->value();
+  s.setValue("quality", quality);
+
+  s.setValue("streamable-subset", IsInStreamingSubset(quality));
```
Comment (hatstand) [inline src/transcoder/transcoderoptionsflac.cpp:60]: Not sure why you're saving this?

File: src/transcoder/transcoderoptionsflac.cpp [hunk 4]
```diff
@@ -37,9 +39,30 @@ void TranscoderOptionsFlac::Load() {
...
+}
+
+bool TranscoderOptionsFlac::IsInStreamingSubset(int level) {
+  // The gstreamer flacenc element defines its own quality settings. The
```
Comment (hatstand) [inline src/transcoder/transcoderoptionsflac.cpp:64]: A link to the FLAC docs would be useful here.

File: src/transcoder/transcoderoptionsflac.cpp (hunk 1 above)
Comment (jbroadus) [reply src/transcoder/transcoderoptionsflac.cpp:46]: Added more info, but open to other suggestions.

File: src/transcoder/transcoderoptionsflac.cpp (hunk 2 above)
Comment (jbroadus) [reply src/transcoder/transcoderoptionsflac.cpp:44]: Done.

File: src/transcoder/transcoderoptionsflac.cpp (hunk 4 above)
Comment (jbroadus) [reply src/transcoder/transcoderoptionsflac.cpp:67]: Done.

File: src/transcoder/transcoderoptionsflac.cpp (hunk 3 above)
Comment (jbroadus) [reply src/transcoder/transcoderoptionsflac.cpp:63]: The transcoder picks up the element properties from the settings. It iterates through each element property and checks for a matching setting entry.
https://github.com/clementine-player/Clementine/blob/master/src/transcoder/transcoder.cpp#L552
