### PR TITLE
Radiobrowser.info: use the url_resolved field for radio stations

### LINKED ISSUE #6988: .pls file from Radio-browser.info stream generates "This appears to be a text file"
When selecting the channel "KBS Classic FM" from Korea in Radio-Browser.info stream, I get a "This appears to be a text file" message from GStreamer.
```
URL handler for QUrl("radiobrowser:c038a859-7be1-11e9-aa30-52543be04c81") returned "http://serpent0.duckdns.org:8088/kbsfm.pls" (query removed)
20:03:38.504 WARN  unknown                          libpng warning: iCCP: known incorrect sRGB profile

0:00:04.715749337 55968 0x559a3f473000 FIXME                    bin gstbin.c:4338:gst_bin_query: implement duration caching in GstBin again
0:00:05.249986982 55968 0x7f08643c94f0 WARN               decodebin gstdecodebin2.c:2852:type_found:<decodebin0> error: This appears to be a text file
0:00:05.250674058 55968 0x7f08643c94f0 WARN               decodebin gstdecodebin2.c:2852:type_found:<decodebin0> error: decodebin cannot decode plain text files
20:03:39.270 ERROR GstEnginePipeline:733            1 "gstdecodebin2.c(2852): type_found (): /GstPipeline:audio-pipeline-1/GstURIDecodeBin:uridecodebin-0/GstDecodeBin:decodebin0:"
20:03:39.271 ERROR GstEnginePipeline:733            1 "decodebin cannot decode plain text files"
20:03:39.271 WARN  GstEngine:719                    Gstreamer error: "This appears to be a text file"
```
When the `.pls` URL is added manually via the `Add Stream` menu, it works however.

Steps to reproduce:
```
Radio-Browser-info --> By Country --> The Republic of Korea --> KBS Classic FM
```
To add it manually from menu : `Playlist | Add Stream`, with URL
```
http://serpent0.duckdns.org:8088/kbsfm.pls
```

Platform: Linux Buster 
```
name -a
Linux debian 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux
```

Clementine built from source:
```
Version 1.4.0rc1-557-g009642d12
```
GStreamer packages installed:
```
buster@debian:~$ dpkg -l | grep gstreamer
ii  gir1.2-gstreamer-1.0:amd64             1.14.4-1                                     amd64        GObject introspection data for the GStreamer library
ii  gstreamer1.0-alsa:amd64                1.14.4-2                                     amd64        GStreamer plugin for ALSA
ii  gstreamer1.0-clutter-3.0:amd64         3.0.26-2                                     amd64        Clutter PLugin for GStreamer 1.0
ii  gstreamer1.0-gl:amd64                  1.14.4-2                                     amd64        GStreamer plugins for GL
ii  gstreamer1.0-gtk3:amd64                1.14.4-1                                     amd64        GStreamer plugin for GTK+3
ii  gstreamer1.0-libav:amd64               1.15.0.1+git20180723+db823502-2              amd64        libav plugin for GStreamer
ii  gstreamer1.0-packagekit                1.1.12-5                                     amd64        GStreamer plugin to install codecs using PackageKit
ii  gstreamer1.0-plugins-bad:amd64         1.14.4-1+deb10u1                             amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.0-plugins-base:amd64        1.14.4-2                                     amd64        GStreamer plugins from the "base" set
ii  gstreamer1.0-plugins-good:amd64        1.14.4-1                                     amd64        GStreamer plugins from the "good" set
ii  gstreamer1.0-plugins-ugly:amd64        1.14.4-1                                     amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.0-pulseaudio:amd64          1.14.4-1                                     amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.0-tools                     1.14.4-1                                     amd64        Tools for use with GStreamer
ii  gstreamer1.0-x:amd64                   1.14.4-2                                     amd64        GStreamer plugins for X11 and Pango
ii  libgstreamer-gl1.0-0:amd64             1.14.4-2                                     amd64        GStreamer GL libraries
ii  libgstreamer-plugins-bad1.0-0:amd64    1.14.4-1+deb10u1                             amd64        GStreamer libraries from the "bad" set
ii  libgstreamer-plugins-base1.0-0:amd64   1.14.4-2                                     amd64        GStreamer libraries from the "base" set
ii  libgstreamer-plugins-base1.0-dev:amd64 1.14.4-2                                     amd64        GStreamer development files for libraries from the "base" set
ii  libgstreamer1.0-0:amd64                1.14.4-1                                     amd64        Core GStreamer libraries and elements
ii  libgstreamer1.0-dev:amd64              1.14.4-1                                     amd64        GStreamer core development files
ii  libreoffice-avmedia-backend-gstreamer  1:6.1.5-3+deb10u7                            amd64        GStreamer backend for LibreOffice
buster@debian:~$ 
```

### PR DESCRIPTION
**Pull request by ctrlaltca**
Some radio stations on radiobrowser.info contain a playlist address in the "url" field.
The radiobrowser API is so kind to provide also a url_resolved field containing the resolved url of the audio stream.
This PR switches from the "url" to the "url_resolved" field to fix playback of those stations.

Fix #6988

### CODE REVIEW

File: src/internet/radiobrowser/radiobrowserservice.cpp [hunk 1]
```diff
@@ -433,7 +433,7 @@ void RadioBrowserService::ResolveStationUrl(const QUrl& original_url) {
     Song ret;
     ret.set_valid(true);
     ret.set_title(item["name"].toString());
-    QUrl url(item["url"].toString());
+    QUrl url(item["url_resolved"].toString());
```
Comment (jbroadus) [inline src/internet/radiobrowser/radiobrowserservice.cpp:436]: Is `url_resolved` always populated? I wonder if we want to fall back on `url` if it's empty.

Comment (ctrlaltca) [reply src/internet/radiobrowser/radiobrowserservice.cpp:436]: The API documentation itself doesn't mark any field as optional: https://de1.api.radio-browser.info/#Struct_station
I had a look at the API source itself and the url_resolved field comes from a database field called "UrlCache" that is used internally for other things, eg. to determine if a station actually works and looking for duplicate stations.
Still, I'm adding the fall back just to stay on the safe side.

**Review by jbroadus — APPROVED** [review]
