### PR TITLE
disconnect GVolumeMonitor signals from GioLister before destroying it

### LINKED ISSUE #5369: Clementine hangs on exit if built with ENABLE_GIO=ON
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Gentoo Linux (amd64)
- Clementine version: 1.3.1, current master

### Expected behaviour / actual behaviour

Clementine should exit normally

### Steps to reproduce the problem (only for bugs)

Build Clementine with ENABLE_GIO=ON
Run Clementine
Try to exit application

Seems to be related to #802 and  #1728

Application seems to hang because GVolumeMonitor is emitting signals in GioLister destructor

### PR DESCRIPTION
**Pull request by Chemrat**
This should fix #5369

### CODE REVIEW

File: src/devices/giolister.cpp [hunk 1]
```diff
@@ -94,11 +94,19 @@ void GioLister::Init() {
...
+  signals_.append(CHECKED_GCONNECT(monitor_, "volume-added", &VolumeAddedCallback, this));
+  signals_.append(CHECKED_GCONNECT(monitor_, "volume-removed", &VolumeRemovedCallback, this));
+  signals_.append(CHECKED_GCONNECT(monitor_, "mount-added", &MountAddedCallback, this));
+  signals_.append(CHECKED_GCONNECT(monitor_, "mount-changed", &MountChangedCallback, this));
+  signals_.append(CHECKED_GCONNECT(monitor_, "mount-removed", &MountRemovedCallback, this));
+}
+
+GioLister::~GioLister()
+{
+  foreach(gulong signal, signals_)
```
Comment (hatstand) [inline src/devices/giolister.cpp]: `for (gulong signal : signals_) {`

File: src/devices/giolister.cpp [hunk 2]
```diff
@@ -94,11 +94,19 @@ void GioLister::Init() {
...
-  CHECKED_GCONNECT(monitor_, "mount-changed", &MountChangedCallback, this);
-  CHECKED_GCONNECT(monitor_, "mount-removed", &MountRemovedCallback, this);
+  signals_.append(CHECKED_GCONNECT(monitor_, "volume-added", &VolumeAddedCallback, this));
+  signals_.append(CHECKED_GCONNECT(monitor_, "volume-removed", &VolumeRemovedCallback, this));
+  signals_.append(CHECKED_GCONNECT(monitor_, "mount-added", &MountAddedCallback, this));
+  signals_.append(CHECKED_GCONNECT(monitor_, "mount-changed", &MountChangedCallback, this));
+  signals_.append(CHECKED_GCONNECT(monitor_, "mount-removed", &MountRemovedCallback, this));
+}
+
+GioLister::~GioLister()
```
Comment (ArnaudBienner) [inline src/devices/giolister.cpp]: Please be consistent with the other part of the file:
GioLister::~GioLister() {
instead of
GioLister::~GioLister()
{

Same for the loop
